1. Write a Python Program to Add Two Matrices?

In [1]:
x=[[1,2,3],
   [45,6,6],
   [3,4,5]]
y=[[11,2,33],
   [2,3,4],
   [34,55,5]]
result = [[0,0,0],
         [0,0,0],
         [0,0,0]]
for i in range(len(x)):
    for j in range(len(x[0])):
        result[i][j]=x[i][j]+y[i][j]
for k in result:
    print(k)

[12, 4, 36]
[47, 9, 10]
[37, 59, 10]


In [2]:
import numpy as np
a = np.array([[1, 2,3], [3, 4,5],[3,45,5],[4,5,6]])
b = np.array([[1, 2,3], [3, 4,5],[3,45,5],[4,5,6]])
c=np.add(a,b)
print(c)

[[ 2  4  6]
 [ 6  8 10]
 [ 6 90 10]
 [ 8 10 12]]


2. Write a Python Program to Multiply Two Matrices?

In [4]:
x=[[1,2,3],
   [45,6,6],
   [3,4,5]]
y=[[11,2,33],
   [2,3,4],
   [34,55,5]]
result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(x)):
    for j in range(len(y[0])):
        for k in range(len(y)):
            result[i][j]+=x[i][k]+y[k][j]
for r in result:
    print(r)

[53, 66, 48]
[104, 117, 99]
[59, 72, 54]


In [5]:
import numpy as np
a = np.array([[1, 2,3], [3, 4,5],[3,45,5]])
b = np.array([[1, 2,3], [3, 4,5],[3,45,5]])
c=np.dot(a,b)
print(c)

[[ 16 145  28]
 [ 30 247  54]
 [153 411 259]]


3. Write a Python Program to Transpose a Matrix

In [6]:
x=[[1,2,3],
   [45,6,6],
   [3,4,5],
   [2,3,4]]
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]
for i in range(len(x)):
    for j in range(len(x[0])):
        result[j][i]=x[i][j]
for k in result:
    print(k)

[1, 45, 3, 2]
[2, 6, 4, 3]
[3, 6, 5, 4]


In [7]:
import numpy as np
a = np.array([[1, 2,3], [3, 4,5],[3,45,5],[4,5,6]])
print(a.transpose())

[[ 1  3  3  4]
 [ 2  4 45  5]
 [ 3  5  5  6]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [8]:
def alphabetical_sorting(l):
    word=l.split(' ')
    word.sort()
    return word

In [9]:
n=str(input('enter string'))

enter stringthe cat is cute


In [10]:
print(alphabetical_sorting(n))

['cat', 'cute', 'is', 'the']


5. Write a Python Program to Remove Punctuation From a String?

In [11]:
def puncutation_remover(l):
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    result=' '
    for i in l:
        if i not in punctuations:
            result+=i
    return result

In [12]:
l=str(input('enter string'))

enter stringis the cat cute? yes it is!


In [13]:
print(puncutation_remover(l))

 is the cat cute yes it is
